name: Tests

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: rootproject/root:6.24.00-conda

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: chmod
      working-directory: .github/workflows
      run: |
        ls -la
        chmod +x ./sendgrid.js
        chmod +x deploy.sh
        chmod +x filter.sh
        chmod +x mail_body.sh 
      
    - name: CutLang Dependencies
      run: |
        apt update
        apt install -y flex bison wget make
                   
    - name: Build CutLang
      working-directory: CLA
      run: |
        root --version
        make
    
    - name: Run Tests
      working-directory: .github/workflows
      run: |
        ./deploy.sh 2>&1 | tee ./raw_output.txt
      
    - name: Filter Output
      working-directory: .github/workflows
      run: |
        ./filter.sh
        cd ../previous; diff raw_output.txt ../workflows/raw_output.txt | tee ../workflows/differences.txt; rm raw_output.txt errors.txt efficacy_charts.txt differences.txt 
        cd ../workflows; cp raw_output.txt errors.txt efficacy_charts.txt differences.txt ../previous/
        mkdir artifacts; mv raw_output.txt errors.txt efficacy_charts.txt differences.txt ./artifacts
        if [ "`cat ./artifacts/errors.txt`" != "Errors: " ]; then
          touch flag
        fi
        ./mail_body.sh

        git --version
        git status

        target_date=`date "+%Y-%m-%d" -d "6 day ago"`
        cur_date=`git log -1 --pretty="format:%cs" ../previous/raw_output.txt`
        tar_date_int=$(date -d $target_date +%s)
        cur_date_int=$(date -d $cur_date +%s)

        if [ $tar_date_int -le $cur_date_int ]; then
          exit 0
        fi

        git config user.email "jinens8@gmail.com"
        git config user.name "bot"

        git add ../previous
        git commit -m "automated update" 
        git push origin ${GITHUB_REF##*/}

    - name: Check for Bad Run Flag
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/workflows/flag"

    - name: SMTP
      uses: peter-evans/sendgrid-action@v1
      if: steps.check_files.outputs.files_exists == 'true'
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: ./.github/workflows/sendgrid.js     
      
    - name: Upload Output File
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests (ubuntu-latest)
        path: ./.github/workflows/artifacts
