name: Tests

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: chmod
      working-directory: .github/workflows
      run: |
        ls -la
        chmod +x ./sendgrid.js
        chmod +x deploy.sh
        chmod +x filter.sh
        chmod +x filter_errors.sh
        chmod +x mail_body.sh 
          
    - name: ROOT Dependencies
      run: |
        sudo apt update ; 
        sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev \
        libxft-dev libxext-dev python libssl-dev ;
        sudo apt-get install gfortran libpcre3-dev \
        xlibmesa-glu-dev libglew1.5-dev libftgl-dev \
        libmysqlclient-dev libfftw3-dev libcfitsio-dev \
        graphviz-dev libavahi-compat-libdnssd-dev \
        libldap2-dev python-dev libxml2-dev libkrb5-dev \
        libgsl0-dev ;
                   
    - name: Build ROOT
      working-directory: .
      run: |
        wget https://root.cern/download/root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        tar -xzvf root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        rm -rf root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
    
      
    - name: CutLang Dependencies
      run: |
        sudo apt update
        sudo apt install -y flex bison wget
                   
    - name: Build CutLang
      working-directory: CLA
      run: |
        source ../root/bin/thisroot.sh; root --version; make
    
    - name: Run Tests
      working-directory: .github/workflows
      run: |
        source ../../root/bin/thisroot.sh; ./deploy.sh 2>&1 | tee ./raw_output.txt
      
    - name: Filter Output
      working-directory: .github/workflows
      run: |
        ./filter.sh
        ./filter_errors.sh
        git pull
        cd ../previous; diff raw_output.txt ../workflows/raw_output.txt | tee ../workflows/differences.txt;
        echo ended tee
        rm raw_output.txt errors.txt efficacy_charts.txt differences.txt;
        echo ended rm
        cd ../workflows;
        mkdir ../previous2;
        echo ended mkdir previous2
        cp -r ../previous/* ../previous2;
        echo ended cp -r
        cp raw_output.txt errors.txt efficacy_charts.txt differences.txt ../previous/;
        echo ended cp raw_output
        mkdir artifacts; mv raw_output.txt errors.txt efficacy_charts.txt differences.txt ./artifacts
        if [ "`cat ./artifacts/errors.txt`" != "Errors: " ]; then
          touch flag
        fi
        ./mail_body.sh

    - name: Update Artifacts
      if: ${{ github.event_name == 'push' }}
      working-directory: .github/workflows
      run: |
        git --version
        git status

        target_date=`date "+%Y-%m-%d" -d "6 day ago"`
        cur_date=`git log -1 --pretty="format:%cs" ../previous2/raw_output.txt`
        tar_date_int=$(date -d $target_date +%s)
        cur_date_int=$(date -d $cur_date +%s)

        echo target_date: $target_date
        echo cur_date: $cur_date

        if [ $tar_date_int -le $cur_date_int ]; then
          exit 0
        fi

        rm -rf ../previous2

        git config user.email "jinens8@gmail.com"
        git config user.name "bot"

        git --version
        git add ../previous
        git --version
        git status
        git commit -m "automated update" 
        git --version
        git status
        git push origin ${GITHUB_REF##*/}
        git --version

    - name: Check for Bad Run Flag
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/workflows/flag"

    - name: SMTP
      uses: peter-evans/sendgrid-action@v1
      if: steps.check_files.outputs.files_exists == 'true'
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: ./.github/workflows/sendgrid.js     
      
    - name: Upload Output File
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests (ubuntu-latest)
        path: ./.github/workflows/artifacts
